### ISSUE TITLE
Delete the navigation menue in the exported png

### ISSUE THREAD

**Issue by g-berthiaume** [anydown/vscode-ganttdown#2]
When using the `export` functionality to convert the gantt into a .png file, the navigation menu still appear in the image. 
Could we remove the interface?

Before
![gantt](https://user-images.githubusercontent.com/19377511/82121138-cf5b3a00-9758-11ea-82ef-8d4736456b58.png)

After
![gantt](https://user-images.githubusercontent.com/19377511/82121220-645e3300-9759-11ea-95e1-2d85b5f597aa.png)

Interesting work ! 
Regards,

**Comment by hashrock** [comment]
Fixed in 0.2.5.
Thanks for reporting.

https://github.com/anydown/anydown-gantt/commit/ba18ec50b037d4c57d01ad35c53c2257ea28ec84
